spring:
  profiles:
    active: dev
  application:
    name: appstore
  cloud:
    config:
      discovery:
        enabled: true
        service-id: APPSTORE
  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: false
  jackson:
    time-zone: Asia/Shanghai

server:
  servlet:
    context-path: /appstore
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
#    关闭敏感端口的操作（防止敏感端口不能被访问）
endpoint:
  sensitive: false

eureka:
  instance:
    #    lease-renewal-interval-in-seconds: 5
    #    lease-expiration-duration-in-seconds: 10
    metadata-map:
      company-name: aitemi
  #    hostname: localhost
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/

logging:
  level:
    com.netflix: DEBUG

management:
  endpoint:
    health:
      show-details: always
      web:
        exposure:
          include: "*"
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://47.104.7.60:13306/qcast_launcher?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: fastcast
    password: eac9a09b3705186cfc6f53265cfd036d
  jpa:
    show-sql: true
server:
  port: 8080

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://vpc-readonly.mysql.rds.aliyuncs.com/qcast_launcher?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: fastcast
    password: eac9a09b3705186cfc6f53265cfd036d

